# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Identify adjustment sets
#'
#' Identify different sets of nodes in a DAG valid for adjustment with respect to 
#' a cause node X and a effect node Y. Based on Zander and Liśkiewicz (2020) algorithm 
#' for finding (minimal) separators and a modified Algorithm 3.1 in Koller (2009, p. 75) 
#' for finding reachable nodes.
#' 
#' @name adjset
#' @param G a n-by-n adjacency matrix of a graph. `G[x, y] = 1` if there is an edge from node `x` to `y`, zero otherwise.
#' @param x,y (integer)
#'   column position of the cause and effect variable, respectively (using zero-based index, from 0 to n-1).
#' @param Z (integer vector)
#'    column positions of conditioning variables (using zero-based index, from 0 to n-1).
#' @param A (logical vector)
#'   indicates the subset of nodes paths must be contained in.
#'   The search along a path ends if visiting a node `i` such that `A[i] = FALSE`.
#' @param name (string) name of adjustment set, see details.
#' @param dmat (optional) a n-by-n adjacency matrix such that `dmat(x, y) = 1` if `x` is an ancestor of `y` in `G`.
#'   Added as an optional argument for speed. If not specified, `areDescendants` and `areAncestors` are called to 
#'   identify the relevant relationships.
#' @param Gx the backdoor graph of `G` w.r.t. `x`.
#' @details
#' The function `areReachable` implements Algorithm 3.1 in Koller (2009, p. 75) and
#' identifies nodes in `G` reachable from `x` given `Z` via active trails in `G`, with the restriction
#' that all nodes on the trail are in `A`. 
#' 
#' The function `find_nearest_adjset` assumes `Z` is a set of nodes separating `x` and `y` in `Gx`, and returns the
#' subset of `Z` reachable from `x` given `Z`, that is the subset of `Z` closest to `x`. 
#' A minimal separator is found by applying `find_nearest_adjset` again w.r.t `y` and the reduced set.
#' 
#' The function `adjset` applies these algorithms to identify different adjustment set: 
#' 
#' - "o": The optimal adjustment set (o-set). If `A` is the set of joint ancestors of `x` and `y` and `Z` equals `A` 
#'   minus any descendant of `x`, the o-set includes all nodes that can be reached from `y` via active paths in `A`
#'   given `Z`. That is the subset of `Z` closest to `y` on every path ending with an arrow into `y`.
#' - "o-min": The minimal O-set. The subset of the o-set reachable from `x`, i.e. a minimal separator of `x` and `y` in the backdoor graph.
#' - "pa-min": The minimal parent set. The subset of the parents of `x` reachable from `y`, 
#'   i.e. i.e. a minimal separator of `x` and `y` in the backdoor graph.
#'   
#' These adjustment sets are defined only when `x` is ancestor of `y`.
#' If that is not the case, the function returns `y` indicating that `x` has no effect on `y`.
#' Additionally, 
#' 
#' - "pa": the set of parents of `x`, read of `G` directly, independently of wheter `x` is an ancestor of `y`.
#' - "pa-if": if `y` is a descendant of `x`, then the set of parents is returned. Otherwise the function returns `y`.
#' 
#' For other values of `name` the function returns either `y` or `Z` (the joint set of descendants of `x` and `y` minus descendants of `x`),
#' which is itself a valid adjustment set.
NULL

isParent <- function(G, x, y) {
    .Call(`_adjset_isParent`, G, x, y)
}

isChild <- function(G, x, y) {
    .Call(`_adjset_isChild`, G, x, y)
}

#' @rdname adjset
#' @export
#' @returns
#' - `areDescendants`: a logical `n`-length vector indicating which nodes are descendants of `nodes`.
areDescendants <- function(G, nodes) {
    .Call(`_adjset_areDescendants`, G, nodes)
}

#' @rdname adjset
#' @export
#' @returns
#' - `areAncestor`: a logical `n`-length vector indicating which nodes are ancestors of `nodes`.
areAncestors <- function(G, nodes) {
    .Call(`_adjset_areAncestors`, G, nodes)
}

isDescendant <- function(G, x, y) {
    .Call(`_adjset_isDescendant`, G, x, y)
}

#' @rdname adjset
#' @export
#' @returns
#' - `areReachable`: a logical vector indicating which nodes in `G` can be reached from `x`
#'    through active paths that traverses only nodes in `A` conditional on `Z`.
areReachable <- function(G, x, Z, A) {
    .Call(`_adjset_areReachable`, G, x, Z, A)
}

#' @rdname adjset
#' @returns
#' - `find_nearest_adjset`: The subset of Z nearest `x` valid for adjustment (assuming Z is a valid adjusment set).
#' @export
find_nearest_adjset <- function(Gx, x, Z, A) {
    .Call(`_adjset_find_nearest_adjset`, Gx, x, Z, A)
}

#' @rdname adjset
#' @export
#' @return
#' - `adjset`: an integer vector with the (zero-indexed) column positions of an adjustment set as given by `name`.
adjset <- function(G, x, y, name, dmat = matrix(0)) {
    .Call(`_adjset_adjset`, G, x, y, name, dmat)
}

